回想在命令式编程下异常处理，通常我们用try-catch，一般有如下几种处理方式：
1. catch里处理异常，如记录错误参数，然后将异常继续抛出
2. 在catch中处理异常，并且吃掉异常，如在遍历集合时，某个项出错，继续后面的处理
3. 在catch中处理异常，并且返回一个值，如不想报错，只返回false，可以继续后面的逻辑
4. 在catch中处理异常，并且包装一个新的异常抛出

下面我们看在Flux里如何处理，处理的逻辑是一样的，只不过我们用Flux的api完成，不用手动try-catch

默认情况下，序列中某个元素出错，就会停止
```
    @Test
    public void testErrorException() {
        //输出：1 2
        Flux.just(1, 2, 3).flatMap(s -> {
            System.out.println(s);
            if (s == 2) {
                throw new RuntimeException();
            }
            return Mono.empty();
        }).subscribe();
    }
```
doOnError可以让我们在错误出现时做一些处理，然后它会进行抛出错误
```
    @Test
    public void testErrorDoOnError() {
        //输出：1 2 doonerror
        Flux.just(1, 2, 3).flatMap(s -> {
            System.out.println(s);
            if (s == 2) {
                throw new RuntimeException();
            }
            return Mono.empty();
        }).doOnError(s -> System.out.println("doonerror")).subscribe();
    }
```
onErrorContinue可以吃掉异常，后面的元素可以继续执行
```
    @Test
    public void testErrorDoOnErrorContinue() {
        //输出：1 2 onerrorcontinue 3
        Flux.just(1, 2, 3).flatMap(s -> {
            System.out.println(s);
            if (s == 2) {
                throw new RuntimeException();
            }
            return Mono.empty();
        }).onErrorContinue((a, b) -> {
            System.out.println("onerrorcontinue");
        }).subscribe();
    }
```
doOnError和onErrorContinue一起使用时，onErrorContinue会先被触发，如果它不抛出异常，doOnError不会被执行
```
    @Test
    public void testErrorDoOnErrorContinueAndDoOnError() {
        //输出：1 2 onerrorcontinue
        Flux.just(1, 2, 3).flatMap(s -> {
            System.out.println(s);
            if (s == 2) {
                throw new RuntimeException();
            }
            return Mono.empty();
        }).doOnError(s -> System.out.println("doonerror"))
                .onErrorContinue((a, b) -> {
                    System.out.println("onerrorcontinue");
                    throw new RuntimeException();
                }).subscribe();
    }
```
onErrorContinue有时候是危险的，我们不希望异常被吃掉，onErrorStop可以阻止下游
```
    @Test
    public void testErrorDoOnErrorStop() {
        //输出：1 2
        Flux.just(1, 2, 3).flatMap(s -> {
            System.out.println(s);
            if (s == 2) {
                throw new RuntimeException();
            }
            return Mono.empty();
        }).onErrorStop().onErrorContinue((a, b) -> {
            System.out.println("onerrorcontinue");
        }).subscribe();
    }
```
onErrorResume可以返回一个新的序列，原序列会停止，后面从新的序列开始
```
    @Test
    public void testErrorDoOnErrorResume() {
        //输出：1 2 4 5 6
        Flux.just(1, 2, 3).flatMap(s -> {
            System.out.println(s);
            if (s == 2) {
                throw new RuntimeException();
            }
            return Mono.empty();
        }).onErrorResume(s -> Flux.just(4, 5, 6)).flatMap(s -> {
            System.out.println(s);
            return Mono.empty();
        }).subscribe();
    }
```
doOnError和onErrorResume一起使用时，doOnError会先被触发
```
    @Test
    public void testErrorDoOnErrorResumeAndDoOnError() {
        //输出：1 2 doonerror onerrorresume
        Flux.just(1, 2, 3).flatMap(s -> {
            System.out.println(s);
            if (s == 2) {
                throw new RuntimeException();
            }
            return Mono.empty();
        }).doOnError(s -> System.out.println("doonerror"))
                .onErrorResume(s -> {
                    System.out.println("onerrorresume");
                    return Mono.empty();
                }).subscribe();
    }
```
onErrorReturn与onErrorResume类似，它用于返回一个值
```
    @Test
    public void testErrorDoOnErrorReturn() {
        //输出：1 2 0
        Flux.just(1, 2, 3).flatMap(s -> {
            System.out.println(s);
            if (s == 2) {
                throw new RuntimeException();
            }
            return Mono.empty();
        }).onErrorReturn(0).flatMap(s -> {
            System.out.println(s);
            return Mono.empty();
        }).subscribe();
    }
```
onErrorMap用于包装一个新的异常抛出
```
    @Test
    public void testErrorDoOnErrorMap() {
        //输出：1 2
        Flux.just(1, 2, 3).flatMap(s -> {
            System.out.println(s);
            if (s == 2) {
                throw new NumberFormatException();
            }
            return Mono.empty();
        }).onErrorMap(s -> new RuntimeException(s)).subscribe();
    }
```